dist: trusty

sudo: required

language: cpp

services:
  - docker

env:
  global:
    - GITHUB_REPO=ldorau/librpma
    - DOCKERHUB_REPO=ldorau/librpma
  matrix:
    - OS=ubuntu OS_VER=19.10 TYPE=normal PUSH_IMAGE=1
    - OS=fedora OS_VER=31    TYPE=normal PUSH_IMAGE=1 AUTO_DOC_UPDATE=1

before_install:
  - echo $TRAVIS_COMMIT_RANGE
  - export HOST_WORKDIR=`pwd`
  - cd utils/docker
  - ./pull-or-rebuild-image.sh

script:
  - ./build.sh

after_success:
  - source ./set-vars.sh
  - if [[ -f $CI_FILE_PUSH_IMAGE_TO_REPO ]]; then ./images/push-image.sh $OS-$OS_VER; fi
